const fs = require('fs');
const content = fs.readFileSync('src/store/transporterStore.ts', 'utf8');

const regex = /export const cargasDisponiblesIniciales: Carga\[\] = \[([\s\S]*?)\]\n\nexport interface Transportista/;

const replacement = \export const cargasDisponiblesIniciales: Carga[] = [
  {
    id: 'carga-maiz-001',
    producto: 'Maíz amarillo',
    kg: 300,
    pago: 600,
    agricultor: 'Pedro Salazar',
    telefonoAgricultor: '987 654 321',
    origen: 'Lauricocha',
    destino: 'Huánuco centro',
    distanciaKm: 78,
    duracionEstimadaMin: 135,
    horaRecojo: '15:30',
    horaEntregaMaxima: '18:30',
    estadoRuta: 'riesgo',
    riesgo: 'MEDIO',
    prioridad: 'URGENTE',
    requiereFrio: false,
    coordenadasOrigen: [-10.073, -76.632],
    coordenadasDestino: [-9.9306, -76.2401],
    motivoBloqueo: null,
  },
  {
    id: 'carga-cafe-001',
    producto: 'Café',
    kg: 200,
    pago: 450,
    agricultor: 'María Torres',
    telefonoAgricultor: '976 111 222',
    origen: 'Leoncio Prado',
    destino: 'Aucayacu',
    distanciaKm: 64,
    duracionEstimadaMin: 110,
    horaRecojo: '15:00',
    horaEntregaMaxima: '17:00',
    estadoRuta: 'bloqueada',
    riesgo: 'GRAVE',
    prioridad: 'RETRASADO',
    requiereFrio: false,
    coordenadasOrigen: [-9.295, -75.995],
    coordenadasDestino: [-8.931, -76.113],
    motivoBloqueo: 'Ruta bloqueada por derrumbe reportado',
  },
  {
    id: 'carga-aguacate-001',
    producto: 'Aguacate',
    kg: 150,
    pago: 380,
    agricultor: 'Rosa Huamán',
    telefonoAgricultor: '965 333 444',
    origen: 'Marañón',
    destino: 'Huánuco centro',
    distanciaKm: 42,
    duracionEstimadaMin: 75,
    horaRecojo: '16:00',
    horaEntregaMaxima: '19:00',
    estadoRuta: 'libre',
    riesgo: 'BAJO',
    prioridad: 'DISPONIBLE',
    requiereFrio: false,
    coordenadasOrigen: [-9.827, -76.109],
    coordenadasDestino: [-9.9306, -76.2401],
    motivoBloqueo: null,
  },
  {
    id: 'carga-cacao-001',
    producto: 'Cacao Orgánico',
    kg: 500,
    pago: 850,
    agricultor: 'Carlos Ruiz',
    telefonoAgricultor: '945 123 456',
    origen: 'Tingo María',
    destino: 'Huánuco centro',
    distanciaKm: 120,
    duracionEstimadaMin: 180,
    horaRecojo: '14:00',
    horaEntregaMaxima: '19:00',
    estadoRuta: 'libre',
    riesgo: 'BAJO',
    prioridad: 'DISPONIBLE',
    requiereFrio: false,
    coordenadasOrigen: [-9.300, -76.000],
    coordenadasDestino: [-9.9306, -76.2401],
    motivoBloqueo: null,
  },
  {
    id: 'carga-limon-001',
    producto: 'Limón Tahití',
    kg: 1000,
    pago: 1200,
    agricultor: 'Ana Silva',
    telefonoAgricultor: '934 987 654',
    origen: 'Ambo',
    destino: 'Huánuco centro',
    distanciaKm: 25,
    duracionEstimadaMin: 45,
    horaRecojo: '17:00',
    horaEntregaMaxima: '18:30',
    estadoRuta: 'riesgo',
    riesgo: 'MEDIO',
    prioridad: 'URGENTE',
    requiereFrio: false,
    coordenadasOrigen: [-10.123, -76.200],
    coordenadasDestino: [-9.9306, -76.2401],
    motivoBloqueo: null,
  },
  {
    id: 'carga-trigo-001',
    producto: 'Trigo',
    kg: 2500,
    pago: 1800,
    agricultor: 'Juan Perez',
    telefonoAgricultor: '999 888 777',
    origen: 'Pachitea',
    destino: 'Huánuco centro',
    distanciaKm: 60,
    duracionEstimadaMin: 120,
    horaRecojo: '13:00',
    horaEntregaMaxima: '17:00',
    estadoRuta: 'libre',
    riesgo: 'BAJO',
    prioridad: 'DISPONIBLE',
    requiereFrio: false,
    coordenadasOrigen: [-9.900, -75.900],
    coordenadasDestino: [-9.9306, -76.2401],
    motivoBloqueo: null,
  }
]

export interface Transportista\;

const newContent = content.replace(regex, replacement);
fs.writeFileSync('src/store/transporterStore.ts', newContent, 'utf8');
console.log('Fixed encoding in transporterStore.ts!');
