import type { Route, Incident } from './routeTypes'

export const mockRoutes: Route[] = [
  {
    id: 'route-001',
    name: 'Huánuco - Amarilis',
    origin: 'Huánuco',
    destination: 'Amarilis',
    status: 'LIBRE',
    estimatedTime: '25 min',
    distance: '8 km',
    recommendation: 'Ruta disponible para traslado agrícola.',
  },
  {
    id: 'route-002',
    name: 'Huánuco - Pillco Marca',
    origin: 'Huánuco',
    destination: 'Pillco Marca',
    status: 'LIBRE',
    estimatedTime: '20 min',
    distance: '6 km',
    recommendation: 'Ruta disponible para traslado agrícola.',
  },
  {
    id: 'route-003',
    name: 'Huánuco - Tingo María',
    origin: 'Huánuco',
    destination: 'Tingo María',
    status: 'RIESGO',
    estimatedTime: '3 h 20 min',
    distance: '120 km',
    incidentType: 'LLUVIA',
    recommendation: 'Conducir con precaución por lluvia intensa.',
  },
  {
    id: 'route-004',
    name: 'Huánuco - Pasco',
    origin: 'Huánuco',
    destination: 'Pasco',
    status: 'BLOQUEADA',
    estimatedTime: 'No disponible',
    distance: '95 km',
    incidentType: 'HUAICO',
    recommendation: 'Evitar esta ruta hasta nueva actualización.',
  },
  {
    id: 'route-005',
    name: 'Amarilis - Mercado de Productores',
    origin: 'Amarilis',
    destination: 'Mercado de Productores',
    status: 'RIESGO',
    estimatedTime: '15 min',
    distance: '4 km',
    incidentType: 'VIA_LENTA',
    recommendation: 'Tránsito lento por alta afluencia de vehículos.',
  },
]

export const mockIncidents: Incident[] = [
  {
    id: 'inc-001',
    routeId: 'route-004',
    routeName: 'Huánuco - Pasco',
    type: 'HUAICO',
    severity: 'HIGH',
    description: 'Huaico reportado en el km 45 de la carretera Huánuco - Pasco.',
    reportedAt: 'Hace 2 horas',
    recommendation: 'Evitar esta ruta por el momento.',
  },
  {
    id: 'inc-002',
    routeId: 'route-003',
    routeName: 'Huánuco - Tingo María',
    type: 'LLUVIA',
    severity: 'MEDIUM',
    description: 'Lluvia intensa en la zona de La Esperanza, visibilidad reducida.',
    reportedAt: 'Hace 30 minutos',
    recommendation: 'Reducir velocidad y encender luces reglamentarias.',
  },
  {
    id: 'inc-003',
    routeId: 'route-005',
    routeName: 'Amarilis - Mercado de Productores',
    type: 'VIA_LENTA',
    severity: 'LOW',
    description: 'Tránsito vehicular denso por horario de comercialización.',
    reportedAt: 'Hace 15 minutos',
    recommendation: 'Tomar la ruta alterna por la avenida principal.',
  },
]
